// AI-powered flashcard generation implementation

import { CardGenerator } from '../interfaces/processors';
import { FlashCard, QualityScore, CardType } from '../types/flashcard';
import { Keyword, ContentChunk } from '../types/content';
import { LocalAIModelService } from '../services/AIModelService';
import { AIModelService } from '../interfaces/ai';

export class AICardGenerator implements CardGenerator {
  private aiService: AIModelService;

  constructor(aiService?: AIModelService) {
    this.aiService = aiService || new LocalAIModelService();
  }

  async generateCards(keywords: Keyword[], context: ContentChunk[]): Promise<FlashCard[]> {
    // Check if AI service is available
    const isAvailable = await this.aiService.isAvailable();
    
    if (!isAvailable) {
      console.warn('AI service unavailable, falling back to rule-based generation');
      return this.fallbackGeneration(keywords, context);
    }

    try {
      const cards = await this.aiService.generateCards(keywords, context);
      
      // Validate and filter generated cards
      const validCards = cards.filter(card => this.validateCardQuality(card).overall >= 0.6);
      
      if (validCards.length === 0) {
        console.warn('No valid cards generated by AI, falling back to rule-based generation');
        return this.fallbackGeneration(keywords, context);
      }

      return validCards;
    } catch (error) {
      console.error('AI card generation failed:', error);
      return this.fallbackGeneration(keywords, context);
    }
  }

  validateCardQuality(card: FlashCard): QualityScore {
    const feedback: string[] = [];
    let clarity = 1.0;
    let relevance = 1.0;
    let difficulty = 0.5; // Default medium difficulty

    // Check clarity
    if (card.front.length < 10) {
      clarity -= 0.3;
      feedback.push('Question is too short');
    }
    if (card.back.length < 5) {
      clarity -= 0.3;
      feedback.push('Answer is too short');
    }
    if (card.front.includes('undefined') || card.back.includes('undefined')) {
      clarity -= 0.5;
      feedback.push('Contains undefined content');
    }

    // Check relevance
    if (card.keywords.length === 0) {
      relevance -= 0.2;
      feedback.push('No keywords associated');
    }
    if (!card.sourceContext || card.sourceContext.length < 20) {
      relevance -= 0.2;
      feedback.push('Insufficient source context');
    }

    // Assess difficulty
    const questionComplexity = this.assessComplexity(card.front);
    const answerComplexity = this.assessComplexity(card.back);
    difficulty = (questionComplexity + answerComplexity) / 2;

    const overall = (clarity + relevance + difficulty) / 3;

    return {
      overall: Math.max(0, Math.min(1, overall)),
      clarity: Math.max(0, Math.min(1, clarity)),
      relevance: Math.max(0, Math.min(1, relevance)),
      difficulty: Math.max(0, Math.min(1, difficulty)),
      feedback
    };
  }

  private assessComplexity(text: string): number {
    const words = text.split(/\s+/).length;
    const sentences = text.split(/[.!?]+/).length;
    const avgWordsPerSentence = words / sentences;
    
    // Simple complexity scoring
    let complexity = 0.3; // Base complexity
    
    if (words > 15) complexity += 0.2;
    if (avgWordsPerSentence > 10) complexity += 0.2;
    if (text.includes('because') || text.includes('therefore') || text.includes('however')) {
      complexity += 0.2;
    }
    if (/[A-Z][a-z]+\s[A-Z][a-z]+/.test(text)) { // Proper nouns
      complexity += 0.1;
    }
    
    return Math.min(1, complexity);
  }

  private fallbackGeneration(keywords: Keyword[], context: ContentChunk[]): FlashCard[] {
    const cards: FlashCard[] = [];
    
    // Generate definition cards for top keywords
    const topKeywords = keywords
      .sort((a, b) => b.importance - a.importance)
      .slice(0, Math.min(5, keywords.length));

    for (const keyword of topKeywords) {
      // Find context containing this keyword
      const relevantContext = context.find(chunk => 
        chunk.text.toLowerCase().includes(keyword.term.toLowerCase())
      );

      if (relevantContext) {
        const card = this.createDefinitionCard(keyword, relevantContext);
        if (card) {
          cards.push(card);
        }
      }
    }

    // Generate question-answer cards from context
    const questionCards = this.generateQuestionCards(keywords, context);
    cards.push(...questionCards);

    return cards;
  }

  private createDefinitionCard(keyword: Keyword, context: ContentChunk): FlashCard | null {
    const sentences = context.text.split(/[.!?]+/).filter(s => s.trim().length > 0);
    const relevantSentence = sentences.find(s => 
      s.toLowerCase().includes(keyword.term.toLowerCase())
    );

    if (!relevantSentence) {
      return null;
    }

    return {
      id: this.generateId(),
      front: `What is ${keyword.term}?`,
      back: relevantSentence.trim(),
      type: CardType.DEFINITION,
      difficulty: this.mapCategoryToDifficulty(keyword.category),
      keywords: [keyword.term],
      sourceContext: context.text.substring(0, 200),
      createdAt: new Date()
    };
  }

  private generateQuestionCards(keywords: Keyword[], context: ContentChunk[]): FlashCard[] {
    const cards: FlashCard[] = [];
    const maxCards = Math.min(3, context.length);

    for (let i = 0; i < maxCards && i < context.length; i++) {
      const chunk = context[i];
      const chunkKeywords = keywords.filter(k => 
        chunk.text.toLowerCase().includes(k.term.toLowerCase())
      );

      if (chunkKeywords.length > 0) {
        const card = this.createQuestionCard(chunk, chunkKeywords);
        if (card) {
          cards.push(card);
        }
      }
    }

    return cards;
  }

  private createQuestionCard(chunk: ContentChunk, keywords: Keyword[]): FlashCard | null {
    const sentences = chunk.text.split(/[.!?]+/).filter(s => s.trim().length > 10);
    
    if (sentences.length < 2) {
      return null;
    }

    // Use first sentence as answer, create question from keywords
    const answer = sentences[0].trim();
    const mainKeyword = keywords[0];
    const question = `Explain the concept related to ${mainKeyword.term}.`;

    return {
      id: this.generateId(),
      front: question,
      back: answer,
      type: CardType.QUESTION_ANSWER,
      difficulty: this.mapCategoryToDifficulty(mainKeyword.category),
      keywords: keywords.map(k => k.term),
      sourceContext: chunk.text.substring(0, 200),
      createdAt: new Date()
    };
  }

  private mapCategoryToDifficulty(category: string): number {
    switch (category.toLowerCase()) {
      case 'fact':
        return 1; // Easy
      case 'definition':
        return 2; // Medium
      case 'concept':
        return 2; // Medium
      case 'process':
        return 3; // Hard
      case 'example':
        return 1; // Easy
      default:
        return 2; // Medium
    }
  }

  private generateId(): string {
    return 'card_' + Date.now() + '_' + Math.random().toString(36).substr(2, 9);
  }
}